// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5EA9EN3NMLvP9FY83KejeaunV_P0eIRA',
    appId: '1:619194818358:web:ea6f9f9e4c229a12dbdd97',
    messagingSenderId: '619194818358',
    projectId: 'stockapp-4f32d',
    authDomain: 'stockapp-4f32d.firebaseapp.com',
    storageBucket: 'stockapp-4f32d.appspot.com',
    measurementId: 'G-0EMWC9172K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmnJaB6mc5bgY5F1BGdPsipBkyn1WduPg',
    appId: '1:619194818358:android:0161531f2da2c576dbdd97',
    messagingSenderId: '619194818358',
    projectId: 'stockapp-4f32d',
    storageBucket: 'stockapp-4f32d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDEUPawzVONhFI1M-d8q7DFA7FJLo7LdY',
    appId: '1:619194818358:ios:08cf0539fc52814bdbdd97',
    messagingSenderId: '619194818358',
    projectId: 'stockapp-4f32d',
    storageBucket: 'stockapp-4f32d.appspot.com',
    iosBundleId: 'com.example.stockapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDEUPawzVONhFI1M-d8q7DFA7FJLo7LdY',
    appId: '1:619194818358:ios:50d6b47c36dad771dbdd97',
    messagingSenderId: '619194818358',
    projectId: 'stockapp-4f32d',
    storageBucket: 'stockapp-4f32d.appspot.com',
    iosBundleId: 'com.example.stockapp.RunnerTests',
  );
}
