// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE0aeRjVyB2qcpvsysWj882HcV9iKEQH0',
    appId: '1:238093381598:web:66fa568d31637d9cdfb74f',
    messagingSenderId: '238093381598',
    projectId: 'stockapp-93e54',
    authDomain: 'stockapp-93e54.firebaseapp.com',
    storageBucket: 'stockapp-93e54.appspot.com',
    measurementId: 'G-E7BDL4C6ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB41QKpLWZHLXmsVL7G3rs1vZGxaEJfGD8',
    appId: '1:238093381598:android:9741e6f4cedd9a3edfb74f',
    messagingSenderId: '238093381598',
    projectId: 'stockapp-93e54',
    storageBucket: 'stockapp-93e54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDndbxuyEAXM8CsWi9OWBX4qczIjYdkRZw',
    appId: '1:238093381598:ios:f974884731ccf577dfb74f',
    messagingSenderId: '238093381598',
    projectId: 'stockapp-93e54',
    storageBucket: 'stockapp-93e54.appspot.com',
    iosBundleId: 'com.example.stockapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDndbxuyEAXM8CsWi9OWBX4qczIjYdkRZw',
    appId: '1:238093381598:ios:f5669dd4f2099879dfb74f',
    messagingSenderId: '238093381598',
    projectId: 'stockapp-93e54',
    storageBucket: 'stockapp-93e54.appspot.com',
    iosBundleId: 'com.example.stockapp.RunnerTests',
  );
}
